name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Kodu GitHub'dan Çek
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Python Ortamını Ayarla
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"  # Python sürümünü buradan ayarlayabilirsin.

    # 3. Gerekli Kütüphaneleri Kur
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. PYTHONPATH Ayarını Yap
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    # 5. Testleri Çalıştır ve Coverage Raporu Al
    - name: Run Tests
      run: pytest --cov=src --cov-report=term-missing
